version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3006:80"
    environment:
            - VITE_API_URL=https://korder.cloud

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - mongo


  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
