services:
  backend:
    container_name: korder-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=production
    networks:
      - korder
    restart: unless-stopped

  frontend:
    container_name: korder-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    # networks:
    #   - korder
    restart: unless-stopped

networks:
  korder:
    external: true
