name: Deploy
on:
  push:
    branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: docker build . -t ghcr.io/${{ github.actor }}/korder-main:latest && docker push ghcr.io/${{ github.actor }}/korder-main:latest
      - name: Deploy to Server
        run: |
          echo "${{ secrets.HOMELAB_SSH_PRIVATE_KEY }}" > key && chmod 600 key
          ssh -i key ${{ secrets.HOMELAB_USER }}@${{ secrets.HOMELAB_HOST }} "cd ${{ secrets.WORK_DIR }} && docker pull ghcr.io/${{ github.actor }}/korder-main:latest && docker run -d -p 80:80 ghcr.io/${{ github.actor }}/korder-main:latest"