name: Deploy Vue to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vue-build
          path: dist

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: vue-build
          path: dist

      - name: Build Docker image
        run: |
          docker build -t korder-main:latest .

      - name: Save Docker image
        run: docker save -o korder-main.tar korder-main:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: korder-main.tar

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Log in to Oracle server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Stop and remove existing container (if any)
            docker stop korder-main || true
            docker rm korder-main || true

            # Remove old image
            docker rmi korder-main:latest || true

      - name: Copy Docker image to Oracle server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'korder-main.tar'
          target: '/home/ubuntu/'

      - name: Load and run Docker container on Oracle server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Load Docker image
            docker load -i /home/ubuntu/korder-main.tar

            # Run the container
            docker run -d --name korder-main -p 3005:80 korder-main:latest
