name: Deploy Vue to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vue-build
          path: dist

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: vue-build
          path: dist

      - name: Build Docker image
        run: |
          docker build -t korder-vue:latest .

      - name: Save Docker image
        run: docker save -o korder-vue.tar korder-vue:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: korder-vue.tar

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Log in to Oracle server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Stop and remove existing container (if any)
            docker stop korder-vue || true
            docker rm korder-vue || true

            # Remove old image
            docker rmi korder-vue:latest || true

      - name: Copy Docker image to Oracle server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'korder-vue.tar'
          target: '/home/ubuntu/'

      - name: Load and run Docker container on Oracle server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Load Docker image
            docker load -i /home/ubuntu/korder-vue.tar

            # Run the container
            docker run -d --name korder-vue -p 3005:80 korder-vue:latest
