name: Build and Deploy
on: push  # trigger on push to main (adjust as needed)
permissions:
  contents: read
  packages: write  # needed to push to GHCR
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-korder-main:latest

      - name: Deploy to Homelab via Cloudflare SSH
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.HOMELAB_HOST }}              # e.g. your-tunnel-hostname
          username: ${{ secrets.HOMELAB_USER }}         # e.g. "ubuntu"
          port: 22                                      # SSH port on homelab (likely 22)
          private_key_value: ${{ secrets.HOMELAB_SSH_PRIVATE_KEY }}
          service_token_id: ${{ secrets.CF_SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.CF_SERVICE_TOKEN_SECRET }}
          commands: |
            docker pull ghcr.io/${{ github.repository_owner }}/my-korder-main:latest
            docker stop vue3app || true && docker rm vue3app || true
            docker run -d --name vue3app --restart unless-stopped -p 3006:3006 ghcr.io/${{ github.repository_owner }}/my-korder-main:latest
